[
  { name: 'refactoring' },
  { name: 'audit' },
  { name: 'security' },
  { name: 'dream' },
  { name: 'showoff' },
  { name: 'emergency' },
  { name: 'insight' },
  { name: 'lib' },
  { name: 'give_project' },
  { name: 'superman' },
  { name: 'take_project' },
  { name: 'transfer' },
  { name: 'claim' },
  { name: 'pilot' },
  { name: 'req_tax' },
  { name: 'req_legal' },
  { name: 'coffee' },
  { name: 'weekend' },
  { name: 'disease' },
  { name: 'water' },
  { name: 'teamlead' },
  { name: 'flowstate' },
  { name: 'crutch' },
  { name: 'crutch' },
  { name: 'crutch' },
];
