({
  addTime: Date.now(),
  settings: {
    type: 'duel',
    playerHandStart: 3,
    playerHandLimit: 3,
    planesNeedToStart: 3,
  },
  round: 1,
  playerList: [
    {
      _code: 1,
      active: true,
      deckList: [
        { type: 'domino', itemType: 'any' },
        { type: 'card', itemType: 'event' },
        { type: 'plane' },
      ],
    },
    {
      _code: 2,
      deckList: [
        { type: 'domino', itemType: 'any' },
        { type: 'card', itemType: 'event' },
        { type: 'plane' },
      ],
    },
  ],
  deckList: [
    {
      type: 'domino',
      itemType: 'any',
      itemList: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [4, 4],
        [4, 5],
        [4, 6],
        [5, 5],
        [5, 6],
        [6, 6],
      ],
    },
    {
      type: 'card',
      itemType: 'event',
      itemList: [
        // {name: 'pilot', playOneTime: true},
        // {name: 'req_tax', playOneTime: true},
        // {name: 'req_legal', playOneTime: true},
        // {name: 'crutch', autoPlay: false},
        // {name: 'crutch', autoPlay: false},
        // {name: 'crutch', autoPlay: false},
        { name: 'coffee' },
        { name: 'weekend' },
        { name: 'rain' },
        { name: 'teamlead' },
        { name: 'flowstate' },
        { name: 'crutch' },
        { name: 'crutch' },
        { name: 'crutch' },
      ],
    },
    {
      type: 'card',
      subtype: 'active',
      itemType: 'event',
    },
    {
      type: 'card',
      subtype: 'drop',
      itemType: 'event',
    },
  ],
  planeList: [
    {
      _code: 1,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': ['Zone[2].ZoneSide[1]'],
          'ZoneSide[2]': ['Zone[4].ZoneSide[1]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': ['Zone[2].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[4].ZoneSide[2]'],
        },
      },
      zoneList: [
        { _code: 1, left: 130, top: 7, itemType: 'any', s: 'bash' },
        {
          _code: 2,
          left: 130,
          top: 100,
          vertical: 1,
          itemType: 'any',
          s: 'db',
        },
        { _code: 3, left: 230, top: 170, itemType: 'any', s: 'db' },
        {
          _code: 4,
          left: 300,
          top: 7,
          vertical: 1,
          itemType: 'any',
          s: 'core',
        },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 100,
          direct: { left: true },
          links: ['Zone[2].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 76,
          direct: { right: true },
          links: ['Zone[4].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 2,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 50, top: 87, itemType: 'any' },
        {
          _code: 2,
          left: 215,
          top: 50,
          vertical: 1,
          double: true,
          itemType: 'any',
        },
        { _code: 3, left: 310, top: 87, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 0,
          direct: { top: true, left: false },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 0,
          direct: { top: false, right: true },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 0,
          top: 175,
          direct: { bottom: false, left: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 425,
          top: 175,
          direct: { bottom: true, right: false },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 3,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[1].ZoneSide[2]', 'Zone[3].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 50, top: 170, itemType: 'any', s: 'css' },
        {
          _code: 2,
          left: 215,
          top: 100,
          vertical: 1,
          itemType: 'any',
          s: 'html',
        },
        { _code: 3, left: 310, top: 170, itemType: 'any', s: 'js' },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 70,
          direct: { left: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
        },
        {
          _code: 2,
          left: 215,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[1]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 425,
          top: 70,
          direct: { right: true },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
        },
      ],
    },
    {
      _code: 4,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 87, itemType: 'any' },
        { _code: 2, left: 280, top: 87, double: true, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 80,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 320,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 80,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 320,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 5,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 87, itemType: 'any' },
        { _code: 2, left: 280, top: 87, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 150,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[2]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 80,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 280,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 6,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
          //'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[1]'],
        },
        'Zone[3]': {
          //'ZoneSide[1]': ['Zone[2].ZoneSide[2]'],
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 50, top: 50, itemType: 'any' },
        {
          _code: 2,
          left: 215,
          top: 50,
          vertical: 1,
          itemType: 'any',
        },
        { _code: 3, left: 310, top: 120, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 140,
          direct: { left: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 30,
          direct: { right: true },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
        },
      ],
    },
    {
      _code: 7,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[4].ZoneSide[1]', 'Zone[4].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[1].ZoneSide[2]', 'Zone[3].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 50, top: 170, itemType: 'any', s: 'css' },
        {
          _code: 2,
          left: 215,
          top: 100,
          vertical: 1,
          itemType: 'any',
          s: 'html',
        },
        { _code: 3, left: 310, top: 170, itemType: 'any', s: 'js' },
        {
          _code: 4,
          left: 180,
          top: 10,
          double: true,
          itemType: 'any',
          s: 'js',
        },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 70,
          direct: { left: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 425,
          top: 70,
          direct: { right: true },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
        },
      ],
    },
    {
      _code: 8,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': ['Zone[4].ZoneSide[1]'],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': ['Zone[4].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[2].ZoneSide[2]'],
        },
      },
      zoneList: [
        {
          _code: 1,
          left: 130,
          top: 7,
          vertical: 1,
          itemType: 'any',
          s: 'db',
        },
        { _code: 2, left: 130, top: 170, itemType: 'any', s: 'bash' },
        {
          _code: 3,
          left: 300,
          top: 100,
          vertical: 1,
          itemType: 'any',
          s: 'core',
        },
        { _code: 4, left: 230, top: 7, itemType: 'any', s: 'db' },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 0,
          direct: { top: true, left: false },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 0,
          direct: { top: true, right: false },
          links: ['Zone[4].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 3,
          left: 0,
          top: 175,
          direct: { bottom: true, left: false },
          links: ['Zone[2].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 425,
          top: 175,
          direct: { bottom: true, right: false },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 9,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[1]', 'Zone[1].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[1]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[4].ZoneSide[1]', 'Zone[4].ZoneSide[2]'],
        },
      },
      zoneList: [
        {
          _code: 1,
          left: 30,
          top: 7,
          vertical: 1,
          double: true,
          itemType: 'any',
          s: 'db',
        },
        { _code: 2, left: 130, top: 40, itemType: 'any', s: 'bash' },
        { _code: 3, left: 230, top: 130, itemType: 'any', s: 'db' },
        {
          _code: 4,
          left: 400,
          top: 100,
          vertical: 1,
          double: true,
          itemType: 'any',
          s: 'core',
        },
      ],
      portList: [
        {
          _code: 1,
          left: 0,
          top: 175,
          direct: { bottom: true, left: false },
          links: ['Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 0,
          direct: { top: true, right: false },
          links: ['Zone[4].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 10,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 87, itemType: 'any' },
        { _code: 2, left: 280, top: 87, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 80,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[2]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 80,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 350,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 11,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 87, double: true, itemType: 'any' },
        { _code: 2, left: 280, top: 87, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 120,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]', 'Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[2]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 120,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[1]', 'Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 280,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 12,
      zoneLinks: {
        'Zone[1]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': [],
        },
        'Zone[3]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[2].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 87, itemType: 'any' },
        { _code: 2, left: 280, top: 87, itemType: 'any' },
        { _code: 3, left: 180, top: 5, double: true, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 80,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 13,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[1].ZoneSide[1]', 'Zone[3].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 105, top: 90, vertical: 1, itemType: 'any' },
        { _code: 2, left: 215, top: 10, vertical: 1, itemType: 'any' },
        { _code: 3, left: 320, top: 90, vertical: 1, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 75,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[3].ZoneSide[1]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 0,
          top: 175,
          direct: { bottom: false, left: true },
          links: ['Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 425,
          top: 175,
          direct: { bottom: true, right: false },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 14,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 10, vertical: 1, itemType: 'any' },
        { _code: 2, left: 180, top: 87, double: true, itemType: 'any' },
        { _code: 3, left: 350, top: 90, vertical: 1, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 215,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[3].ZoneSide[1]'],
          t: 'any',
        },
        {
          _code: 3,
          left: 80,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[1].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 4,
          left: 215,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 15,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[1]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[1]'],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 90, vertical: 1, itemType: 'any' },
        { _code: 2, left: 180, top: 87, double: true, itemType: 'any' },
        { _code: 3, left: 350, top: 90, vertical: 1, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 80,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 215,
          top: 0,
          direct: { top: true },
          links: ['Zone[2].ZoneSide[1]', 'Zone[2].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 3,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[3].ZoneSide[1]'],
          t: 'any',
        },
      ],
    },
    {
      _code: 16,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[2]', 'Zone[4].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[2]', 'Zone[4].ZoneSide[2]'],
        },
      },
      zoneList: [
        { _code: 1, left: 80, top: 90, vertical: 1, itemType: 'any' },
        { _code: 2, left: 180, top: 160, double: true, itemType: 'any' },
        { _code: 3, left: 350, top: 90, vertical: 1, itemType: 'any' },
        { _code: 4, left: 215, top: 10, vertical: 1, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 80,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 350,
          top: 0,
          direct: { top: true },
          links: ['Zone[3].ZoneSide[1]'],
          t: 'any',
        },
      ],
    },
    {
      _code: 17,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': ['Zone[1].ZoneSide[2]'],
          'ZoneSide[2]': ['Zone[3].ZoneSide[1]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[4].ZoneSide[2]'],
        },
      },
      zoneList: [
        {
          _code: 1,
          left: 50,
          top: 7,
          vertical: 1,
          double: true,
          itemType: 'any',
          s: 'db',
        },
        { _code: 2, left: 50, top: 170, itemType: 'any', s: 'bash' },
        { _code: 3, left: 230, top: 170, itemType: 'any', s: 'db' },
        {
          _code: 4,
          left: 300,
          top: 7,
          vertical: 1,
          double: true,
          itemType: 'any',
          s: 'core',
        },
      ],
      portList: [
        {
          _code: 1,
          left: 175,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 425,
          top: 0,
          direct: { top: true, right: false },
          links: ['Zone[4].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 3,
          left: 425,
          top: 175,
          direct: { bottom: true, right: false },
          links: ['Zone[3].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
    {
      _code: 18,
      zoneLinks: {
        'Zone[2]': {
          'ZoneSide[1]': [],
          'ZoneSide[2]': ['Zone[1].ZoneSide[1]', 'Zone[3].ZoneSide[1]'],
        },
        'Zone[3]': {
          'ZoneSide[1]': ['Zone[4].ZoneSide[2]'],
          'ZoneSide[2]': [],
        },
      },
      zoneList: [
        { _code: 1, left: 50, top: 90, vertical: 1, itemType: 'any' },
        { _code: 2, left: 160, top: 10, vertical: 1, itemType: 'any' },
        { _code: 3, left: 270, top: 90, vertical: 1, itemType: 'any' },
        { _code: 4, left: 380, top: 10, vertical: 1, itemType: 'any' },
      ],
      portList: [
        {
          _code: 1,
          left: 50,
          top: 0,
          direct: { top: true },
          links: ['Zone[1].ZoneSide[1]'],
          t: 'any',
          s: 'core',
        },
        {
          _code: 2,
          left: 380,
          top: 175,
          direct: { bottom: true },
          links: ['Zone[4].ZoneSide[2]'],
          t: 'any',
          s: 'core',
        },
      ],
    },
  ],
});
